codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "10...50"

  status:
    project:
      default:
        target: auto
        threshold: 1%

    patch:
      default:
        target: 70%
        threshold: 0%
        only_pulls: true

comment:
  layout: "reach,diff,files"
  behavior: default
  require_changes: false

ignore:
  - "build-logic/**"
  - "**/build/**"